"""Schemas for AI Question Generation Pipeline (Phase 7).

Defines structured generation requests, candidate contracts, duplicate reports,
validation findings, and human review workflows.
"""

from __future__ import annotations

import datetime
import uuid
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from app.modules.admin.enums import AIGenerationJobStatus
from app.modules.assessments.enums import (
    CognitiveComplexityLevel,
    QuestionResponseType,
)


class CandidateOptionPayload(BaseModel):
    """An option generated by AI for single_choice or multiple_choice questions."""

    model_config = ConfigDict(from_attributes=True)

    content: str
    is_correct: bool = False
    order_index: int = 0
    explanation: str | None = None
    misconception_type: str | None = None
    distractor_rationale: str | None = None


class CandidateSkillMapping(BaseModel):
    """Skill competency tag tied to the question candidate."""

    model_config = ConfigDict(from_attributes=True)

    skill_id: uuid.UUID
    skill_code: str | None = None
    skill_name: str | None = None
    role: str = "primary"  # "primary" or "secondary"
    weight: float = 1.0


class CandidateGenerationMetadata(BaseModel):
    """Provenance and execution metrics for an AI-generated question candidate."""

    model_config = ConfigDict(from_attributes=True)

    model: str
    prompt_template_version: str
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    estimated_cost_usd: float = 0.0
    latency_ms: int = 0
    is_simulation: bool = False
    generated_at: datetime.datetime = Field(
        default_factory=lambda: datetime.datetime.now(datetime.UTC)
    )


class DuplicateCheckReport(BaseModel):
    """Duplicate detection audit report comparing against existing questions and stimuli."""

    model_config = ConfigDict(from_attributes=True)

    is_duplicate: bool = False
    status: str = "unique"  # "unique", "possible_duplicate", "exact_duplicate"
    similarity_score: float = 0.0
    matched_question_id: uuid.UUID | None = None
    matched_prompt: str | None = None
    message: str = "Aucun doublon détecté dans la banque de questions."


class AIReviewReport(BaseModel):
    """Second-pass AI quality and pedagogical critique (read-only audit)."""

    model_config = ConfigDict(from_attributes=True)

    quality_score: float = 85.0
    naturalness_score: float = 90.0
    pedagogical_alignment: str = "high"
    distractor_quality: str | None = None
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    suggested_improvements: list[str] = Field(default_factory=list)
    reviewed_at: datetime.datetime = Field(
        default_factory=lambda: datetime.datetime.now(datetime.UTC)
    )


class GeneratedQuestionCandidate(BaseModel):
    """Structured question candidate draft generated by AI."""

    model_config = ConfigDict(from_attributes=True)

    candidate_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    modality: str = "reading"
    prompt: str
    instructions: str | None = None
    response_type: str = QuestionResponseType.SINGLE_CHOICE.value
    target_cefr: str = "B2"
    difficulty_rating: int = 450
    item_difficulty: int = 3  # 1-5 scale
    cognitive_complexity: str = CognitiveComplexityLevel.INTERPRETATION.value
    points: int = 1
    penalty_points: int = 0
    task_type_id: uuid.UUID | None = None
    task_type_code: str | None = None
    format_spec_version: str | None = None
    option_count: int | None = None

    # Stimulus handling
    stimulus_id: uuid.UUID | None = None
    stimulus_title: str | None = None
    stimulus_content: str | None = None
    stimulus_mode: str = "generate_new"  # "generate_new", "existing_stimulus", "supplied_text"
    source_attribution: str | None = None

    # Components
    options: list[CandidateOptionPayload] = Field(default_factory=list)
    skill_mappings: list[CandidateSkillMapping] = Field(default_factory=list)
    scoring_payload: dict[str, Any] | None = None
    explanation: str | None = None

    # Pipeline Reports
    generation_metadata: CandidateGenerationMetadata
    duplicate_check: DuplicateCheckReport = Field(default_factory=DuplicateCheckReport)
    validation_report: dict[str, Any] | None = None
    ai_review: AIReviewReport | None = None

    # Status in generation review stage
    status: str = "pending_review"  # "pending_review", "accepted", "rejected"


class AIQuestionGenerationRequest(BaseModel):
    """Input payload to request AI-assisted question generation."""

    modality: str = "reading"
    task_type_id: uuid.UUID | None = None
    task_type_code: str | None = None
    response_type: str = QuestionResponseType.SINGLE_CHOICE.value
    target_cefr: str = "B2"
    difficulty_rating: int | None = None
    cognitive_complexity: str = CognitiveComplexityLevel.INTERPRETATION.value
    topic: str | None = None
    option_count: int | None = Field(
        default=None,
        ge=2,
        le=6,
        description=(
            "Requested number of answer options for choice-based formats. "
            "Clamped to the task-type range declared in the question format registry."
        ),
    )

    stimulus_mode: str = "generate_new"  # "generate_new", "existing_stimulus", "supplied_text"
    stimulus_id: uuid.UUID | None = None
    supplied_stimulus_text: str | None = None
    source_attribution: str | None = None

    target_skill_ids: list[uuid.UUID] = Field(default_factory=list)
    questions_per_stimulus: int = Field(default=1, ge=1, le=4)
    count: int = Field(default=1, ge=1, le=10)
    temperature: float = Field(default=0.7, ge=0.0, le=1.5)
    model: str = "models/gemini-3.5-flash"
    api_key_override: str | None = None
    force_simulation: bool = False


class AIBatchGenerationResponse(BaseModel):
    """Response returned when generating a batch of candidate questions."""

    batch_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    candidates: list[GeneratedQuestionCandidate] = Field(default_factory=list)
    total_requested: int
    total_generated: int
    valid_candidates_count: int
    invalid_candidates_count: int
    generation_time_ms: int
    summary: str


class AIGenerationJobCreateRequest(AIQuestionGenerationRequest):
    """Payload to queue an asynchronous AI generation batch.

    Mirrors the synchronous request so both entrypoints stay interchangeable.
    ``api_key_override`` is accepted for parity but is deliberately stripped
    before persistence -- a secret must never be written to the jobs table.
    """


class AIGenerationJobResponse(BaseModel):
    """Polling contract for an asynchronous AI generation batch."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    status: AIGenerationJobStatus
    task_type_code: str | None = None
    modality: str
    target_cefr: str
    requested_count: int
    error_message: str | None = None
    started_at: datetime.datetime | None = None
    completed_at: datetime.datetime | None = None
    created_at: datetime.datetime
    updated_at: datetime.datetime
    is_terminal: bool = False
    result: AIBatchGenerationResponse | None = None


class AIGenerationJobCreateResponse(BaseModel):
    """Returned when a batch is accepted for background processing."""

    job: AIGenerationJobResponse
    poll_url: str


class CandidateCreateDraftRequest(BaseModel):
    """Payload to commit an accepted candidate into a persistent draft Question."""

    candidate: GeneratedQuestionCandidate
    section_id: uuid.UUID | None = None


class CandidateReviewRequest(BaseModel):
    """Payload to trigger an on-demand second-pass AI review of a candidate."""

    candidate: GeneratedQuestionCandidate
    api_key_override: str | None = None
    force_simulation: bool = False


class CandidateRegenerateRequest(BaseModel):
    """Payload to regenerate specific parts of a draft question candidate or question draft."""

    component: str = "distractors"  # "distractors", "prompt", "explanation"
    custom_instructions: str | None = None
    temperature: float = Field(default=0.7, ge=0.0, le=1.5)
    model: str = "models/gemini-3.5-flash"
    api_key_override: str | None = None
    force_simulation: bool = False


class CatalogOption(BaseModel):
    """Static ``(code, label)`` pair for a picklist field such as stimulus kinds."""

    model_config = ConfigDict(extra="forbid")

    code: str
    label: str


class TaskFormatCatalogEntry(BaseModel):
    """A single official TEF task format and everything needed to author it."""

    model_config = ConfigDict(extra="forbid")

    code: str
    module: str
    module_label: str
    name: str
    admin_hint: str
    stimulus_kind: str
    stimulus_kind_label: str
    requires_stimulus: bool
    allowed_response_types: list[str]
    default_response_type: str
    option_count_min: int
    option_count_max: int
    prompt_guidance: str


class TaskFormatCatalogResponse(BaseModel):
    """Server-driven catalogue backing the admin generation wizard.

    The frontend renders every selector from this payload instead of
    hard-coding formats, so adding a task format never requires a frontend
    release.
    """

    total_formats: int
    modules: list[CatalogOption]
    stimulus_kinds: list[CatalogOption]
    formats: list[TaskFormatCatalogEntry]


class AIStimulusGenerationRequest(BaseModel):
    """Payload to generate a specialized TEF stimulus (multi-document, table, audio script, passage)."""

    modality: str = "reading"
    task_type_code: str = "document_matching"
    task_type_id: uuid.UUID | None = None
    target_cefr: str = "B2"
    topic: str | None = None
    format: str = "multi_document"  # "multi_document", "table", "passage", "audio_transcript"
    temperature: float = Field(default=0.7, ge=0.0, le=1.5)
    model: str = "models/gemini-3.5-flash"
    api_key_override: str | None = None
    force_simulation: bool = False


class AIStimulusCandidate(BaseModel):
    """A generated stimulus candidate before or after saving to database."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID | None = None
    title: str
    content_text: str
    text_format: str = "markdown"  # "plain", "markdown", "dialogue", "table"
    modality: str = "reading"
    target_cefr: str = "B2"
    word_count: int = 0
    source_attribution: str | None = None
    task_type_code: str | None = None
    sub_documents: list[dict[str, str]] = Field(default_factory=list)
    generation_metadata: CandidateGenerationMetadata

